language: generic
env:
    - PYVER=2.7 DEBUGVER=""
    - PYVER=2.7 DEBUGVER="--debug"
    - PYVER=3.6 DEBUGVER=""
    - PYVER=3.6 DEBUGVER="--debug"
os:
    - osx
osx_image: xcode-6.4

before_install:
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$PYVER pytest tk=8.5.*
    - conda install -n test-environment numpy>=1.13 libnetcdf expat
    - source activate test-environment
    - bash build.sh
script:
    - source activate test-environment
    - python setup.py test

