language: generic
os:
    - osx
osx_image: xcode-6.4
sudo: false

before_install:
    - bash setup_build.sh

install:
    - conda build-all ./recipes --matrix-condition "numpy >=1.11" "python >=2.7,<3|>=3.5" "r-base ==3.3.2|==3.4.1"

